[project]
name            = "climkit"
version         = "0.1.1"
description     = "ClimKit toolkit"
authors         = [{ name = "VITO" }]
readme          = "README.md"
requires-python = ">=3.12"

[build-system]
build-backend = "hatchling.build"
requires      = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["src/climkit"]


[tool.pixi.package.host-dependencies]
hatchling = "==1.26.3"

[tool.pixi.dependencies]
climkit = { path = "." }

[tool.pixi.package.run-dependencies]
aiohttp           = ">=3.12.13,<4"
alembic           = ">=1.16.2,<2"
dask              = ">=2025.5.1,<2026"
esgf-pyclient     = ">=0.3.1,<0.4"
fastparquet       = ">=2024.11.0,<2025"
h5netcdf          = ">=1.6.1,<2"
ipykernel         = ">=6.29.5,<7"
joblib            = ">=1.5.1,<2"
netcdf4           = ">=1.7.2,<2"
numpy             = ">=2.1.3,<3"
pandas            = ">=2.3.0,<3"
psycopg2          = ">=2.9.10,<3"
pydantic          = ">=2.11.7,<3"
pydantic-settings = ">=2.9.1,<3"
scipy             = ">=1.15.2,<2"
sqlalchemy        = ">=2.0.41,<3"
toml              = ">=0.10.2,<0.11"
tqdm              = ">=4.67.1,<5"
xarray            = ">=2025.6.1,<2026"
ruff              = ">=0.12.0,<0.13"
cdsapi            = ">=0.7.6,<0.8"
shapely           = ">=2.1.1,<3"
httpx             = ">=0.28.1,<0.29"
loguru            = ">=0.7.3,<0.8"
geoalchemy2       = ">=0.17.1,<0.18"
python-graphviz   = ">=0.21,<0.22"
prefect           = ">=3.4.6,<4"
opentelemetry-api = ">=1.34.1,<2"
graphviz          = ">=13.0.1,<14"
cyclopts          = ">=3.19.0,<4"
pytest            = ">=8.4.0,<9"
mypy              = ">=1.16.1,<2"
pytest-dotenv     = ">=0.5.2,<0.6"
pyproj            = ">=3.7.1,<4"
typer             = ">=0.12.5,<0.13"
matplotlib        = ">=3.10.3,<4"
cartopy           = ">=0.24.0,<0.25"
plotly            = ">=6.1.2,<7"
geopandas         = ">=1.1.0,<2"
rasterio          = ">=1.4.3,<2"
rasterstats       = ">=0.20.0,<0.21"
rioxarray         = ">=0.19.0,<0.20"
seaborn           = ">=0.13.2,<0.14"
whenever          = ">=0.5.2,<0.9"
cfchecker         = ">=4.1.0,<5"

# [tool.pixi.pypi-dependencies]
# climkit = { path = ".", editable = true }


[tool.pixi.package]
name    = "climkit"
authors = ["Robin Houdmeyers <robin.houdmeyers@vito.be>"]

[tool.pixi.package.build.backend]
name    = "pixi-build-python"
version = "*"

[tool.pixi.workspace]
channels  = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]
preview   = ["pixi-build"]
